name: Release to Test action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
#  release:
#      types: [created]        
#  workflow_call:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: LinearInputControlSolution 
#      BUILD_ENVIRONMENT_URL:
#        description: 'Build environment url.'
#        type: string
#        required: true      
#      PRODUCTION_ENVIRONMENT_URL: 
#        description: 'Production environment url.'
#        type: string
#        required: true
#      CLIENT_ID: 
#        description: 'The client id'
#        type: string
#        required: true
#      TENANT_ID: 
#        description: 'The tenant id'
#        type: string
#        required: true
        
env:
      #Update your values here
      BUILD_ENVIRONMENT_URL: 'https://orgaaf3ed47.crm.dynamics.com/'  # 20230502Dev
      PRODUCTION_ENVIRONMENT_URL: 'https://orgc147b5b9.crm.dynamics.com/'  # 20230502Test
      CLIENT_ID: 'a88b1599-590d-4b7a-ace1-229dea7fc826'
      TENANT_ID: 'c9f44141-61a3-483a-b157-783e86287e36'     
      
permissions:
  contents: write
jobs:
  convert-to-managed:
    runs-on: ubuntu-latest
    # or you can say runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: solutions/LinearInputControlSolution
        solution-file: out/solutions/LinearInputControlSolution.zip
        solution-type: Unmanaged

#    - name: Import solution as unmanaged to build env
#      uses: microsoft/powerplatform-actions/import-solution@v0
#      with:
#        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
#        app-id: ${{env.CLIENT_ID}}
#        client-secret: ${{ secrets.PowerPlatformSPN }}
#        tenant-id: ${{env.TENANT_ID}}
#        solution-file: out/solutions/MySolution.zip
#        force-overwrite: true
#        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: LinearInputControlSolution
        managed: true
        solution-output-file: out/ship/MySolution_managed.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/LinearInputControlSolution_managed.zip

  release-to-test:
    needs: [ convert-to-managed ]
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/
        
    - name: Import solution to test env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.PRODUCTION_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: out/release/MySolution_managed.zip
        force-overwrite: true
        publish-changes: true
        managed: true
